// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMu10Jx0PrOss2Wwg6MpCY7jI-ATE1w6U',
    appId: '1:1059741491399:android:1fc5256f4f8e063231dee2',
    messagingSenderId: '1059741491399',
    projectId: 'car-rental-app-4cd53',
    storageBucket: 'car-rental-app-4cd53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj1tq63eulkArcXUOhfX75_g_doUR6mSE',
    appId: '1:1059741491399:ios:143fd0adc1c763db31dee2',
    messagingSenderId: '1059741491399',
    projectId: 'car-rental-app-4cd53',
    storageBucket: 'car-rental-app-4cd53.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );
}
/*

Platform  Firebase App Id
android   1:1059741491399:android:1fc5256f4f8e063231dee2
ios       1:1059741491399:ios:143fd0adc1c763db31dee2

*/